version: 0.0
os: linux
files:
  - source: /Dotnet6MvcLogin
    destination: /var/www/myapp
permissions:
  - object: /var/www/myapp
    pattern: "**"
    owner: root
    group: root
  - object: /var/www/myapp/bin/Debug/net6.0/*.dll
    owner: root
    group: root
hooks:
  # BeforeInstall:
  #   - location: scripts/stop_service.sh
  #     timeout: 180
  #     runas: root
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: scripts/start_service.sh
      timeout: 180
      runas: root
