version: 0.0
os: linux
files:
  - source: /Dotnet6MvcLogin
    destination: /var/www/myapp
permissions:
  - object: /var/www/myapp
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: scripts/stop_service.sh
      timeout: 180
      runas: ec2-user
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 180
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_service.sh
      timeout: 180
      runas: ec2-user